# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deadletter < Formula
  desc "Local-first message observability — SMTP, Kafka, Redis, webhooks in one binary"
  homepage "https://github.com/peixotomdb/deadletter"
  version "3.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.2/deadletter_3.5.2_darwin_amd64.tar.gz"
      sha256 "6b78be56350be33bd7e662ab217b9f883e40439418c61a2b6b05d6cc794bb0af"

      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.2/deadletter_3.5.2_darwin_arm64.tar.gz"
      sha256 "226a8013827592976ba551e16f5239b38fae3346ff86a45f3ce60d9b36495a0d"

      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.2/deadletter_3.5.2_linux_amd64.tar.gz"
      sha256 "04ad23e9e69e8a733e7034ed6219c156fc644e9591f46d632c6ecd72e3d90ea0"
      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.2/deadletter_3.5.2_linux_arm64.tar.gz"
      sha256 "225c462a92092cec163bd4796dfb62deadf214a7833b04d88181fc72ad92414e"
      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
      end
    end
  end

  service do
    run [opt_bin/"deadletter", "up", "--smtp", ":1025", "--http", ":8025"]
    keep_alive true
    working_dir var/"deadletter"
    log_path var/"log/deadletter.log"
    error_log_path var/"log/deadletter.err.log"
  end

  test do
    assert_match(/deadletter v?\d+\.\d+\.\d+/, shell_output("#{bin}/deadletter version"))
  end
end
