# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deadletter < Formula
  desc "Local-first message observability — SMTP, Kafka, Redis, webhooks in one binary"
  homepage "https://github.com/peixotomdb/deadletter"
  version "3.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.3/deadletter_3.5.3_darwin_amd64.tar.gz"
      sha256 "7a0e02e1b906c728e20759b3430c4d6933f5ded15c572d1f5885f0d0b001f01e"

      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
        (var/"deadletter").mkpath
        (var/"log").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.3/deadletter_3.5.3_darwin_arm64.tar.gz"
      sha256 "2cca7be00741e39a79f87715e0c0273156793bcaeff9156c48c9735ab80d2569"

      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
        (var/"deadletter").mkpath
        (var/"log").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.3/deadletter_3.5.3_linux_amd64.tar.gz"
      sha256 "fcfdd10dab4e05a956ae80f4f1a3d980858663192f5651fd630467becf599824"
      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
        (var/"deadletter").mkpath
        (var/"log").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deadletter-engine/homebrew-deadletter/releases/download/v3.5.3/deadletter_3.5.3_linux_arm64.tar.gz"
      sha256 "636b3b26e01632a29eea63417404bd3ceceaf1d0f731bbddb2bd83b779c28763"
      define_method(:install) do
        bin.install "deadletter"
        bin.install "deadletterctl" if File.exist?("deadletterctl")
        (var/"deadletter").mkpath
        (var/"log").mkpath
      end
    end
  end

  service do
    run [opt_bin/"deadletter", "up", "--smtp", ":1025", "--http", ":8025"]
    keep_alive true
    working_dir var/"deadletter"
    log_path var/"log/deadletter.log"
    error_log_path var/"log/deadletter.err.log"
  end

  test do
    assert_match(/deadletter v?\d+\.\d+\.\d+/, shell_output("#{bin}/deadletter version"))
  end
end
